// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/questions": {
            "get": {
                "description": "Berilgan ID yoki fan ID bo‘yicha savollarni olish",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Savollarni olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Savol IDsi",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fan IDsi",
                        "name": "subject_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Savol turi",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetQuestionsResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/questions/create": {
            "post": {
                "description": "Yangi savol qo'shish uchun API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Yangi savol yaratish",
                "parameters": [
                    {
                        "description": "Savol yaratish ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateQuestionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/questions/delete/{id}": {
            "delete": {
                "description": "Berilgan ID bo‘yicha savolni o‘chirish",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Savolni o‘chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Savol IDsi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/questions/image/upload": {
            "post": {
                "description": "Rasmni serverga yuklab, Minio'ga saqlaydi va URL qaytaradi",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Faylni yuklash",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Yuklanadigan rasm fayli",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Yuklangan rasm URL'si",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Faylni yuklab olishda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/questions/update/{id}": {
            "put": {
                "description": "Berilgan ID bo‘yicha savolni yangilash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Savolni yangilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Savol IDsi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Savolni yangilash ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateQuestionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/questions/upload": {
            "post": {
                "description": "Foydalanuvchi Excel faylini yuklab, uni serverda qayta ishlash",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Faylni yuklash va tahlil qilish",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Excel fayl",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/model.QuestionsStatus"
                        }
                    },
                    "400": {
                        "description": "Faylni yuklashda yoki saqlashda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students": {
            "get": {
                "description": "Berilgan ID bo‘yicha talabani yoki barcha talabalarni olish",
                "tags": [
                    "Students"
                ],
                "summary": "Talabalar ma'lumotlarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Talabaning unikal ID'si (Majburiy emas, agar berilmasa barcha talabalar qaytariladi)",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Talabalar ma'lumotlari",
                        "schema": {
                            "$ref": "#/definitions/model.GetStudentsResp"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/create": {
            "post": {
                "description": "Yangi talabani ro‘yxatga olish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Talaba yaratish",
                "parameters": [
                    {
                        "description": "Talaba ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateStudentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreateStudentResp"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri ma'lumot kiritildi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/delete/{id}": {
            "delete": {
                "description": "Berilgan ID bo‘yicha talabani o‘chirish",
                "tags": [
                    "Students"
                ],
                "summary": "Talabani o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Talabaning unikal ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Muvaffaqiyatli o‘chirildi",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/results": {
            "get": {
                "description": "Berilgan kun va fanlarga mos keluvchi talabalarning natijalarini qaytaradi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Talabalarning natijalarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Natija kuni",
                        "name": "day",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Birinchi fan ID si",
                        "name": "subject1_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ikkinchi fan ID si",
                        "name": "subject2_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Talabalarning natijalari",
                        "schema": {
                            "$ref": "#/definitions/model.GetStudentsResultResp"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/update/{id}": {
            "put": {
                "description": "Berilgan ID bo‘yicha talabani yangilash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Talaba ma'lumotlarini yangilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Talabaning unikal ID'si",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Yangilangan talaba ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateStudentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Muvaffaqiyatli yangilandi",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri ma'lumot kiritildi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/upload": {
            "post": {
                "description": "Excel fayl orqali talabalar ma'lumotlarini yuklash",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Talabalar ro'yxatini yuklash",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Excel fayl (XLSX format)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Talabalar muvaffaqiyatli yuklandi",
                        "schema": {
                            "$ref": "#/definitions/model.StudentsStatus"
                        }
                    },
                    "400": {
                        "description": "Fayl yuklashda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/students/{student_id}/result": {
            "get": {
                "description": "Retrieves the result of a student based on student_id and template_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Get student result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "template_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetStudentResultResp"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/subjects/create": {
            "post": {
                "description": "Yangi fan qo‘shish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "Fan yaratish",
                "parameters": [
                    {
                        "description": "Yangi fan ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSubjectReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Muvaffaqiyatli qo‘shildi",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri ma'lumot kiritildi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/subjects/get": {
            "get": {
                "description": "Agar ID berilsa, shu fanni, aks holda barcha fanlarni qaytaradi",
                "tags": [
                    "Subjects"
                ],
                "summary": "Fan(lar) ma'lumotlarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fan ID'si (Majburiy emas, agar berilmasa barcha fanlar qaytariladi)",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Fanlar ma'lumotlari",
                        "schema": {
                            "$ref": "#/definitions/model.GetSubjectsResp"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/subjects/update/{id}": {
            "put": {
                "description": "Berilgan ID bo‘yicha fanni yangilaydi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "Fan nomini yangilash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fan IDsi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Yangi fan nomi",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/templates/check": {
            "post": {
                "description": "Ushbu endpoint talabaga tegishli test javoblarini tekshirish uchun ishlatiladi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Talabaning test natijalarini tekshirish",
                "parameters": [
                    {
                        "description": "Talabaning test javoblarini tekshirish uchun ma'lumot",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CheckStudentTestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test natijalari muvaffaqiyatli tekshirildi",
                        "schema": {
                            "$ref": "#/definitions/model.Result"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri ma'lumot kiritildi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/templates/create": {
            "post": {
                "description": "Yangi test template yaratish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Template yaratish",
                "parameters": [
                    {
                        "description": "Template ma'lumotlari",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTemplateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Muvaffaqiyatli yaratildi",
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri ma'lumot kiritildi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Serverda xatolik",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/templates/get": {
            "get": {
                "description": "Student ID va sana bo‘yicha shablonni yuklab olish",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Student shablonini yuklab olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Talaba ID",
                        "name": "student_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kun (YYYY-MM-DD format)",
                        "name": "day",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shablon fayli",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Xato so‘rov",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CheckStudentTestReq": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionAnswer"
                    }
                },
                "day": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "model.CreateQuestionReq": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_image_url": {
                    "type": "string"
                },
                "option_image_url": {
                    "$ref": "#/definitions/model.Option"
                },
                "options": {
                    "$ref": "#/definitions/model.Option"
                },
                "question_image_url": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.CreateStudentReq": {
            "type": "object",
            "properties": {
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "subject1": {
                    "type": "string"
                },
                "subject2": {
                    "type": "string"
                }
            }
        },
        "model.CreateStudentResp": {
            "type": "object",
            "properties": {
                "student_id": {
                    "type": "string"
                }
            }
        },
        "model.CreateSubjectReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "model.CreateTemplateReq": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "model.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.GetQuestionsResp": {
            "type": "object",
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Question"
                    }
                }
            }
        },
        "model.GetStudentResultResp": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StudentResult"
                    }
                }
            }
        },
        "model.GetStudentsResp": {
            "type": "object",
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Student"
                    }
                }
            }
        },
        "model.GetStudentsResultResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "students_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StudentReslt"
                    }
                }
            }
        },
        "model.GetSubjectsResp": {
            "type": "object",
            "properties": {
                "subjects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Subject"
                    }
                }
            }
        },
        "model.Incorrect": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "nomer": {
                    "type": "integer"
                }
            }
        },
        "model.Option": {
            "type": "object",
            "properties": {
                "a": {
                    "type": "string"
                },
                "b": {
                    "type": "string"
                },
                "c": {
                    "type": "string"
                },
                "d": {
                    "type": "string"
                }
            }
        },
        "model.Question": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_image_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "option_image_url": {
                    "$ref": "#/definitions/model.Option"
                },
                "options": {
                    "$ref": "#/definitions/model.Option"
                },
                "question_image_url": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.QuestionAnswer": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "model.QuestionResult": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "model.QuestionsStatus": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "integer"
                },
                "incorrect": {
                    "type": "integer"
                },
                "incorrect_questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Incorrect"
                    }
                }
            }
        },
        "model.Result": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "integer"
                },
                "incorrect": {
                    "type": "integer"
                },
                "percent": {
                    "type": "number"
                }
            }
        },
        "model.Status": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Student": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "subject1": {
                    "type": "string"
                },
                "subject2": {
                    "type": "string"
                }
            }
        },
        "model.StudentReslt": {
            "type": "object",
            "properties": {
                "ball": {
                    "type": "number"
                },
                "day": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionResult"
                    }
                },
                "student_id": {
                    "type": "string"
                },
                "subject1": {
                    "type": "string"
                },
                "subject2": {
                    "type": "string"
                }
            }
        },
        "model.StudentResult": {
            "type": "object",
            "properties": {
                "ball": {
                    "type": "number"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.QuestionResult"
                    }
                },
                "template_id": {
                    "type": "string"
                }
            }
        },
        "model.StudentsStatus": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "integer"
                },
                "incorrect": {
                    "type": "integer"
                },
                "incorrect_students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Student"
                    }
                }
            }
        },
        "model.Subject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.UpdateQuestionReq": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_image_url": {
                    "type": "string"
                },
                "option)image_url": {
                    "$ref": "#/definitions/model.Option"
                },
                "options": {
                    "$ref": "#/definitions/model.Option"
                },
                "question_image_url": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.UpdateStudentReq": {
            "type": "object",
            "properties": {
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "subject1": {
                    "type": "string"
                },
                "subject2": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
