services:

  postgres-db:
    container_name: postgres_edutest
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - edutest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - edutest
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres-db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]

  service:
    container_name: edu_test
    build: .
    ports:
      - "8080:8080"
    networks:
      - edutest
    depends_on:
      - postgres-db
      - migrate
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:8081"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  edutest:
    external: true

volumes:
  db:
    driver: local
